[tool.bumpversion]
current_version = "1.2.1"
commit = true
tag = true

[[tool.bumpversion.files]]
filename = "package.json"
search = "\"version\": \"{current_version}\""
replace = "\"version\": \"{new_version}\""

[[tool.bumpversion.files]]
filename = "res/com.gamestarmechanic.app.metainfo.xml"
# This crude regex will break if the release tag contains any "/" or ">" characters.
search = "<release\\s([^>]+\\s)*version=\"{current_version}\\+next\"[^\\/>]*"
replace = "<release version=\"{new_version}\" date=\"{now:%Y-%m-%d}\" type=\"stable\""

